version: '3.7'

services:

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT:-5432}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  postgres_data:
